from setuptools import setup
from setuptools import find_packages

from codelife.setting import VERSION

with open("README.md", "r", encoding="utf-8") as f:
    LONG_DESCRIPTION = f.read()
setup(name='codelife',
      version=VERSION,
      description="that's code life generated by pypi_seed",
      long_description="Powered by py4ever team!",
      author='levin',
      author_email='levinmhliu@gmail.com',
      url='https://blog.csdn.net/geeklevin',
      install_requires=["renxianqi"],
      license='Apache License 2.0',
      packages=find_packages(),
      platforms=["all"],
      entry_points={
          'console_scripts': [
              'cl = codelife.main:main',
              'codelife = codelife.main:main',
              'codelife-cli = codelife.main:main'
          ]
      },
      classifiers=[
          'Intended Audience :: Developers',
          'Operating System :: OS Independent',
          'Natural Language :: Chinese (Simplified)',
          'Programming Language :: Python',
          'Programming Language :: Python :: 2',
          'Programming Language :: Python :: 2.7',
          'Programming Language :: Python :: 3',
          'Programming Language :: Python :: 3.5',
          'Programming Language :: Python :: 3.6',
          'Programming Language :: Python :: 3.7',
          'Programming Language :: Python :: 3.8',
          'Programming Language :: Python :: 3.9',
          'Topic :: Software Development :: User Interfaces',
          'Topic :: Software Development :: Build Tools',
          'Topic :: Text Editors :: Integrated Development Environments (IDE)',
      ],
      )
